### ISSUE TITLE
Models used for Cifar10 eval

### ISSUE THREAD

**Issue by agoodge** [sesmae/ZOC#1]
Hello,

I am trying to run the cifar10_eval.py file. What models do you load in lines 121 and 129?

Thanks

**Comment by sesmae** [comment]
line 124 loads the [pretrained CLIP model with ViT-B32 architecture](https://github.com/openai/CLIP/blob/main/clip/clip.py#L129). Line 129 loads our fine-tuned decoder. You need to run train_decoder.py first. Then, line 129 can load the weights from the dumped model.

**Comment by agoodge** [comment]
Thank you for your reply! Is there no pre-trained fine-tuned decoder available in your code?
