### ISSUE TITLE
Data leakage

### ISSUE THREAD

**Issue by gitfabianmeyer** [sesmae/ZOC#2]
Why are you removing the semantic labels from the topk-token (e.g line 86 in cifar10_eval.py)? This makes sense for in-distribution data, but in the case of out-of-distribution data, you would not know this label and "punish" the generator for generating a very fitting label, or am I missing something here?

**Comment by sesmae** [comment]
Thank you for your interest in our work. You are right. The correct version would be `unique_entities = list(set(topk_tokens) - set(seen_labels))` in line 86 which is also used in cifar100_eval.py.  Note that the reported result for cifar10 is based on the correct version. I updated cifar10_eval.py
